#!/bin/sh

mkdir -p boot etc .ssh .config/transmission-daemon

rsync -au ~/.profile                      ~/cfg
rsync -au ~/.config/nvim                  ~/cfg/.config
rsync -au ~/.config/tmux                  ~/cfg/.config
rsync -au ~/.config/git                   ~/cfg/.config
rsync -au ~/.config/mutt                  ~/cfg/.config
rsync -au ~/.config/msmtp                 ~/cfg/.config
rsync -au ~/.config/notmuch               ~/cfg/.config
rsync -au ~/.config/isyncrc               ~/cfg/.config
rsync -au ~/.config/mpv                   ~/cfg/.config
rsync -au ~/.config/transm*/settings.json ~/cfg/.config/transmission-daemon
rsync -au ~/.ssh/config                   ~/cfg/.ssh
rsync -au /boot/limine.conf               ~/cfg/boot/limine.conf

doas rsync -au /etc/wpa_supplicant/wpa_supplicant.conf ~/cfg/etc
doas rsync -au /etc/doas.conf                          ~/cfg/etc
doas rsync -au /etc/asound.conf                        ~/cfg/etc
doas rsync -au /etc/inittab                            ~/cfg/etc
doas chown "$USER" ~/cfg/etc/*
