# verbose: yes

timeout: 5

/Alpine Linux
	protocol: linux
	kernel_path: boot():/vmlinuz-lts
	module_path: boot():/initramfs-lts
	cmdline: cryptroot=/dev/sda3 cryptdm=root root=/dev/mapper/root rootfstype=ext4 quiet ipv6.disable=1 audit=0 nowatchdog
